language: php

php:
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - ~/cphalcon

install:
  - composer self-update
  - cd ~/ && rm -rf cphalcon && git clone -b 3.4.x -q --depth=1 https://github.com/phalcon/cphalcon.git && cd cphalcon/build && ./install
  - echo 'extension = "phalcon.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - php --ri phalcon

before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer install --no-interaction
  - composer update --no-interaction

script:
  - ./vendor/bin/codecept run integration
