language: php
php:
- 7.2
- 7.3
sudo: false
env:
  global:
  - secure: J/lTndjebzIWJZjbT8cpw38pQ8ra/KMdGcw0Zit7xdTB/bJTL/dZpRiYz2rPBRC3zuVoLhOwYv7XQPE/neHX8lrOmt1YygWLfYQERQxYna2/FgcHjN1+E1/wvZZddLP/ZQOoFGiwGZoBXKOmidsX56+aESrSxyLJGThDTe+sXu6P7cpEB6ILGXJnFnl65FtTG5/Osf69dxyzikjI/REePwhPYo2HzKZFfARyFFbMs/10IKBQB2hKxW5qnI7RHv5oY/lMOhmt1iNdvyyJ1A5h4Rv1wkSkUSvZFARkNtlrOQp0jsZ5VJDiQdvrczTODA1m8GXIsGFtIKnxQVZhHpEOAMe4FXVZjO0tYZIJQpy2Pg+4cq/tiwc8fx9M6fdvqTLmT35MIv0BbBZIzHAQgC6i7VFhDZuy9ac04jNlmEaazAyM1RM6HXGUgh3/OkWsI9z/wzCfzGh5xRRSXwmT6by746jSVrfWBPVPe2KZ26KOZIC+QMWmDzhQI4Rq231QID3k+naMSimZejpqZRrkC4ODahjtvHGxVakCAtw6Z/W1hbyXjjPGTXNLpwNC14SNgmmiwvOT9/xck/kszGO6De+dz37pIiNe+EtkbLHE42kBRgAFYAMwTL8Cso+u0r29ZponcLCvq5wLL89YLN+CVy2WjbKRrz6l7DP1h/wVUXCNg9Y=
  - secure: v/3JaUSzUWQQhTtEfhWfUOuCOFa7CImQwAIaky5rAsifx8hVFtTLKG+6nXg6Z3GNbPEaepmoLMtMt4HSY3k6mAY8OeK2fGmHZY8xOgXVI11amS30nKAa+pg8kjr92eh0Sm0aRppZhFL9tqVXUALA00ROFV4Qf5oEQkHSNfdkoIoEjmcr5jQPgLyCGKd6wMwH2FSyI5ON6hAcy12ZNokJ0n1UnLSJYX1XdlyyNKNT61Lh6uPU9cJF2kB9Lre/aSomFQTvm0M+GOeJzSiHRlsPiTUvsradB9ZCAkbPttCN3/rDvW1XjicN4hQNMkiNSGXBe1MiMj+nFZM7rRKTSiTI1hzW3yugYMOJRyjDlTAbrZPcfA08lsZ3ikTcLcP7/5JCpCNM5STNF+wh+yqzigz/s4KjpZ7PtdbU7/yDJ6M7nZZHlVOD/4y8ULVbVcZTfc22IjVdmgf/I1q48DN1Xz+n/DKNm+VsAmS7Ot4dtgQKUjVnNYZDhCetKlhPqAZah4n1H/1i0ubiJ1ZvWfhDC+oVGl0zpXjOHOxrWkVltvpm7qg60oJ0+VPtsCOiPJG6oiS+xMNbLLzF3vP64zfd2qUmT5z2vIGMeFM3EeqntUIj/0xulyVyXILduSirE1I4JLnvo2t9y4tJM/Gzn2U2M3rLdUdLJfQ+XXpq/G7hTCXAeeU=
cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"
  - "~/cphalcon"
install:
- composer self-update
- cd ~/ && rm -rf cphalcon && git clone -b 3.4.x -q --depth=1 https://github.com/phalcon/cphalcon.git
  && cd cphalcon/build && ./install
- echo 'extension = "phalcon.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
- php --ri phalcon
before_script:
- cd $TRAVIS_BUILD_DIR
- composer install --no-interaction
- composer update --no-interaction
script:
- "./vendor/bin/codecept run integration"
